services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Randim
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DatabaseInit:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
volumes:
  postgres_data:
